### ISSUE TITLE
Put Toolbar Button Into Address Bar

### ISSUE THREAD

**Issue by Rictusempra** [rugk/offline-qr-code#104] opened 2018-06-21 14:50 UTC
This can be done in Firefox with Page Action API

**Comment by Rictusempra** [comment] 2018-06-21 15:30
@ENT8R 
1. More convenient to use when it goes on Android
1. Make toolbar area less crowded but keep button reachable immediately
1. A little bit closer if you have just typed in address bar by focusing with mouse

**Comment by rugk** [comment] 2018-06-21 17:03
Duplicate of https://github.com/rugk/offline-qr-code/issues/26

**Closed by rugk** 2018-06-21 17:03 UTC
