### ISSUE TITLE
Support define text template for generate similar QRs

### ISSUE THREAD

**Issue by qrqhuang** [rugk/offline-qr-code#281] opened 2022-07-23 08:52 UTC
## Background
I always generate qr code from a standard schema , like `schema://xxxxx?orderNo=xxx`,
and should change the variable `orderNo` for app test purpose.
Now every time I must modify the template variable in my notes , then paste to this extension.
This is a boring job.

## Proposed solution
Below the qr interface, add some lines with template.  And user can choose it then fill into text area.
After that , they can modify variable in extension directly.
It should be great if this settings can be synced too.

## Additional context
![image](https://user-images.githubusercontent.com/17166063/180597947-4d9f1a2e-a32b-4573-bd5c-c40c246fe97b.png)

**Comment by qrqhuang** [comment] 2022-07-29 18:19
@rugk #213 Seems like similar, but I'm not sure what's the final solution you determined .
This issue can be close first.

**Comment by rugk** [comment] 2022-07-29 21:47
Duplicate of https://github.com/rugk/offline-qr-code/issues/213

**Closed by rugk** 2022-07-29 21:47 UTC
Labels: enhancement
