### ISSUE TITLE
Automatically retrieve text from clipboard and generate QR - (pl) Automatycznie pobieraj tekst ze schowka i generuj QR

### ISSUE THREAD

**Issue by GrupaIMEX** [rugk/offline-qr-code#314] opened 2023-11-01 17:04 UTC
## Proposed solution
(PL) Automatycznie pobieraj tekst ze schowka i generuj QR
(EN) Automatically retrieve text from clipboard and generate QR
(en) There is already a function - use automatically selected text - and here you can insert - automatically use text from the contents of the clipboard.

**Comment by rugk** [comment] 2023-11-01 21:59
Thanks for your report, but this is already implemented.

Just go to the settings either by right-clicking on the add-on and choosing “Manage add-on” or by going to `about:addons` (the Firefox add-on management manually) and finding the add-on. Then click on settings:
![grafik](https://github.com/rugk/offline-qr-code/assets/11966684/d3b5cab9-c2da-4646-87f9-0a805d35edfe)

There you can enable “Automatically use text selected on the website” to automatically use the selected text (instread of the current URL, if given):
![grafik](https://github.com/rugk/offline-qr-code/assets/11966684/a5edfa2e-e795-4bd4-a01c-88f04e5007bd)

Now that I reread your issue I see you found this already.
To always use the clipboard yes, this is a planned feature and tracked in https://github.com/rugk/offline-qr-code/issues/282. There are also some PRs, but they are being stuck, oh well…

**Comment by rugk** [comment] 2023-11-01 22:00
Duplicate of https://github.com/rugk/offline-qr-code/issues/282

**Closed by rugk** 2023-11-01 21:59 UTC
Labels: enhancement

**Comment by GrupaIMEX** [comment] 2023-11-03 22:07
Tak chodzi o schowek  
     
      
       
        Dnia 01 listopada 2023 23:00 rugk ***@***.***&gt; napisał(a):
       
    
       
         
 Thanks for your report, but this is already implemented. 
 Just go to the settings either by right-clicking on the add-on and choosing “Manage add-on” or by going to  about:addons  (the Firefox add-on management manually) and finding the add-on. Then click on settings:  
 user-images.githubusercontent.com 
 There you can enable “Automatically use text selected on the website” to automatically use the selected text (instread of the current URL, if given):  
 user-images.githubusercontent.com 
 Now that I reread your issue I see you found this already.  
To always use the clipboard yes, this is a planned feature and tracked in  github.com #282 . There are also some PRs, but they are being stuck, oh well…
