### ISSUE TITLE
Can QR code button live in ... Page Actions?

### ISSUE THREAD

**Issue by NebularNerd** [rugk/offline-qr-code#236] opened 2019-12-04 14:17 UTC
Great addon, works as it should without issue. This is just a would be nice thing, would you be able to add an option to add it to the ... (page action) menu in the address bar? It's not an icon I need everyday on the main addon section but tucked away on the page actions would be a handy place to have it ready for action :)

Thanks, Andy.

**Comment by rugk** [comment] 2019-12-04 17:59
Duplicate of https://github.com/rugk/offline-qr-code/issues/26

TL;DR is: Unfortunately it would require all users to either manually hide the one or the other button. So we cannot really make it optional. :thinking: 

And this follows the Firefox Photon design guidelines.

>  tucked away on the page actions would be a handy place to have it ready for action :)

You can also tuck away the icon in the toolbar into the overflow menu.

**Closed by rugk** 2019-12-04 17:59 UTC
Labels: duplicate, enhancement
