### ISSUE TITLE
QR code icon in address bar

### ISSUE THREAD

**Issue by KAGEYAM4** [rugk/offline-qr-code#335] opened 2024-10-12 12:24 UTC
## Background
https://addons.mozilla.org/en-US/firefox/addon/qr-code-address-bar/ shows icon in addressbar. It looks more part of firefox browser than a extension. Also helps save space in extension list.

**Comment by rugk** [comment] 2024-10-16 17:35
Unfortunately, this goes against the design guidelines: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface 

> Use a page action when the action relates to the current page. Use a browser action when the action relates to the browser as a whole or to many pages. For example:

Also it's statically defined, one cannot enable one or the other dynamically…

Finally, this is also a duplicate:

**Comment by rugk** [comment] 2024-10-16 17:36
Duplicate of https://github.com/rugk/offline-qr-code/issues/236

**Closed by rugk** 2024-10-16 17:36 UTC
Labels: duplicate, enhancement
