### ISSUE TITLE
Space is not efficiently used when in overflow menu

### ISSUE THREAD

**Issue by Gitoffthelawn** [rugk/offline-qr-code#239] opened 2020-01-24 11:28 UTC
## Bug description
When the toolbar button is placed in Firefox's overflow menu, the space available is not used efficiently.

Although the horizontal width seems to be (currently) restricted by Firefox, there is much whitespace around the QR code.  This is true when SVG mode is used

When canvas mode is used, the left and right sides of the QR code are cropped.

May be related to: https://github.com/rugk/offline-qr-code/issues/208

## Steps to reproduce
Add toolbar button to Firefox's overflow menu.  Generate QR codes.

### Actual behavior
See above.

### Expected behavior
Use the space available efficiently to maximize the size of the QR code.

## System
Windows, Firefox 72.0.2, QR Code Generator 1.6

**Comment by rugk** [comment] 2020-01-24 13:36
Duplicate of https://github.com/rugk/offline-qr-code/issues/208

**Closed by rugk** 2020-01-24 13:36 UTC
Labels: bug

**Comment by rugk** [comment] 2020-01-24 13:42
Yeah that is currently a problem with some settings.
You can at least work around it by adjusting the size in the settings or selecting a different size in the settings.

BTW, next time: A screenshot would have been very useful. 😃
