### ISSUE TITLE
Can we have a function to READ QR Codes as well

### ISSUE THREAD

**Issue by TsukiZero** [rugk/offline-qr-code#289] opened 2022-10-17 17:12 UTC
Of course, read and show the content in text form, not "automatically go there", due to risks involved.

**Comment by rugk** [comment] 2022-10-19 11:51
It's unfortunately harder to implement, I have to say.

**Comment by rugk** [comment] 2022-10-19 11:51
Duplicate of https://github.com/rugk/offline-qr-code/issues/52

**Closed by rugk** 2022-10-19 11:51 UTC
Labels: enhancement
