### ISSUE TITLE
To disable it in context menu

### ISSUE THREAD

**Issue by Hochiss** [rugk/offline-qr-code#264] opened 2020-12-04 11:12 UTC
## Background
Firefox extension context menu is getting messy.

## Proposed solution
please give an option in preference to disable it in context menu

## Alternatives
That was the reason I uninstalled another QR code extension.

Thanks!

**Comment by rugk** [comment] 2020-12-04 11:24
Yeah, it's only one entry, but it's a valid feature request. This is a dupe of https://github.com/rugk/offline-qr-code/issues/157 though, so see there for how to implement it. (Note this is an easy issue, so a PR would be gladly appreciated.)

**Comment by rugk** [comment] 2020-12-04 11:24
Duplicate of https://github.com/rugk/offline-qr-code/issues/157

**Closed by rugk** 2020-12-04 11:24 UTC
Labels: enhancement
