### ISSUE TITLE
Extract information from a QR Code picture (.svg / .png / etc. )

### ISSUE THREAD

**Issue by IoanMarin** [rugk/offline-qr-code#278] opened 2022-04-14 15:28 UTC
## Background

 * Currently, one can read a QR Code - generated on a device with "Offline QR Code Generator" add-on - for example by using a smartphone's camera, using a QR Code reader app installed on the smartphone.
 * This means that transferring information from a device having the "Offline QR Code Generator" add-on to a smartphone is currently possible.
 * What it is missing: transferring information from a smartphone to a device that has the "Offline QR Code Generator" add-on.

## Proposed solution

 * One could take a picture of a QR Code displayed on a smartphone - for example by using a webcam.
 * The new feature would be: to be able to extract the information from that picture ( .svg / .png / ... ) ( containing the QR Code) using this add-on ("Offline QR Code Generator")

## Alternatives

 * Transferring information through WiFi / Bluetooth / NFC - could be an alternative. But in my opinion they are not totally safe, and  using WiFi and Bluetooth imply transferring files between the two devices. Also NFC is not implemented on all mobile devices.
 * Because the "Offline QR Code Generator" add-on implies a connection-less information transfer, the transfer should be totally safe and pretty fast too.

## Additional context

 * To remove any suspicion, the permission to be able to read files (pictures containing QR Codes) could be optional: In order to enable it the user could add this permission to the add-on manually.

**Comment by rugk** [comment] 2022-04-17 12:35
Duplicate of https://github.com/rugk/offline-qr-code/issues/52

**Comment by rugk** [comment] 2022-04-17 12:36
Yup, this is a very good idea, and already tracked in https://github.com/rugk/offline-qr-code/issues/52, however, would mostly be a big new feature and require a totally new lib etc.

Surely a good idea though, IMHO.

**Closed by rugk** 2022-04-17 12:35 UTC
Labels: enhancement
