### ISSUE TITLE
Add shortcut icon to the address bar

### ISSUE THREAD

**Issue by Haltarys** [rugk/offline-qr-code#302] opened 2023-02-15 13:05 UTC
## Background
The addon button isn't easily accessible from the toolbar.

## Proposed solution
Add a button in the address bar (next to the ⭐ icon to bookmark the page)

## Alternatives
Pinning the addon to the toolbar sort of does the same job.

**Comment by rugk** [comment] 2023-02-15 23:02
Thanks to your feature report and I see you want to access the add-on button easier.
However, your solution is basically duplicating the existing toolbar icon, as you say in your alternative:
> Pinning the addon to the toolbar sort of does the same job.

For the [technical record](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface): 
* The address bar button you propose is called a page action.
* The toolbar button is called a browser action.

The thing is [we follow the official guidelines here](https://extensionworkshop.com/documentation/develop/user-experience-best-practices/#give-users-what-they-need-where-they-need-it) on what UI element should be used. Duplicating the functionality, while technically possible, would not be a good UX, as it would be only confusing and not consistent with how other features and add-ons (say UBlock origin or so) work.

As said:
> Pinning the addon to the toolbar sort of does the same job.

Yeah, I guess that is the way to go.

> The addon button isn't easily accessible from the toolbar.

That is true and I have no way to pin it by default there (obviously maybe as too many add-ons would do that), so obviously I also don't want to annoy people and clutter the UI with buttons that they may not need. It is easiiily pinnable and AFAIK many people do that for the add-ons they wanna use (more often).

As such, I consider this closed, as there is nothing I can do here anymore.
Also, this is a duplicate of https://github.com/rugk/offline-qr-code/issues/236 and https://github.com/rugk/offline-qr-code/issues/236.

As I just saw in https://github.com/rugk/offline-qr-code/issues/26#issuecomment-385182811 BTW (gosh this is years-old), I once tried implementing it as an optional feature at least and that failed.

**Closed by rugk** 2023-02-15 23:02 UTC
Labels: enhancement
